Repository Arquisoft/lomap_en3b, pull requests merged in 2023-05, with the labels that each got.

#90 Update of the folder's structure and name
  webapp/src/App.js
  webapp/src/components/Map.js
  webapp/src/handlers/podAccess.js
  webapp/src/handlers/podHandler.js
Labels: enhancement

#91 solved bug having to click twice to login
  .gitignore
  webapp/.idea/.gitignore
  webapp/src/views/loginView.js
Labels: bug, enhancement

#97 Tests
  .github/workflows/lomap_en3b.yml
  webapp/.env
  webapp/package.json
  webapp/public/yellow1Location.svg
  webapp/src/components/Filters.js
  webapp/src/components/Header.js
  webapp/src/components/InfoList.js
  webapp/src/components/List.jsx
  webapp/src/components/LogOut.js
  webapp/src/components/Map.js
  webapp/src/tests/DetailedLocationView.test.js
  webapp/src/tests/Filter.test.js
  webapp/src/tests/Header.test.js
  webapp/src/tests/InsertLocation.test.js
  webapp/src/tests/LogOut.test.js
  webapp/src/tests/Profile.test.js
  webapp/src/views/mapView.js
Labels: tests

#100 Final documentation
  .idea/.name
  docs/.asciidoctor/diagram/DeploymentOverview.png.cache
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.html
  docs/07_deployment_view.adoc
  docs/07_deployment_view.html
  docs/09_design_decisions.adoc
  docs/DeploymentOverview.png
  docs/FriendsContent.png
  docs/UserCustomizesPrivateMapPrivate.png
  docs/UserLogin.png
  webapp/public/index.html
  webapp/public/pinYellowTransLocation.svg
  webapp/src/App.js
Labels: documentation
